AWSTemplateFormatVersion: 2010-09-09

# This CloudFormation template demonstrates a problem Im having with multiple policy conditions.

Parameters:

  RequiredOwnerTag:
    Type: String
    Default: MyTeam
    Description: The value for the 'Owner' tag which must be present on all resources we create, modify, or delete.

  RolePrefix:
    Type: String
    Default: MyTeam
    Description: The first few letters of the role names that our principal will be allowed to create, update, and delete.


Resources:

  # This policy needs multiple conditions.  But how do you set them with YAML?
  EamplePolicy1:
    Type: AWS::IAM::ManagedPolicy
    Properties: 
      ManagedPolicyName: ExamplePolicy1
      PolicyDocument: 
        Version: 2012-10-17
        Statement: 
          - Effect: Allow
            Action: 
              - iam:CreateRole
              - iam:AttachRolePolicy
              - iam:DetachRolePolicy
            Resource: 
              - !Sub arn:aws:iam::${AWS::AccountId}:role/${RolePrefix}*
            Condition:
              StringEquals:
                iam:PermissionsBoundary: !Ref PermissionBoundaryPolicy
            Condition:
              StringEquals: 
                iam:RequestTag/Owner: !Ref RequiredOwnerTag

  # Here I'm trying with a YAML array...
  # ...But I got an error saying it was malformed.
  # EamplePolicy2:
  #   Type: AWS::IAM::ManagedPolicy
  #   Properties: 
  #     ManagedPolicyName: ExamplePolicy2
  #     PolicyDocument: 
  #       Version: 2012-10-17
  #       Statement: 
  #         - Effect: Allow
  #           Action: 
  #             - iam:CreateRole
  #             - iam:AttachRolePolicy
  #             - iam:DetachRolePolicy
  #           Resource: 
  #             - !Sub arn:aws:iam::${AWS::AccountId}:role/${RolePrefix}*
  #           Condition:
  #             - StringEquals:
  #                 iam:PermissionsBoundary: !Ref PermissionBoundaryPolicy
  #             - StringEquals: 
  #                 iam:RequestTag/Owner: !Ref RequiredOwnerTag

            

  #  This is a permission boundary.
  PermissionBoundaryPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties: 
      ManagedPolicyName: PermissionBoundaryPolicyExample
      PolicyDocument: 
        Version: 2012-10-17
        Statement: 
          Effect: Allow
          Action: 
            - s3:*
            - iam:List*
          Resource: 
            - "*"
